services:
  rethinkdb:
    image: rethinkdb
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    networks:
      - rethinkdb-net

  spark-builder:
    build:
      context: ./spark
      dockerfile: Dockerfile.builder
    volumes:
      - ./spark:/opt/spark/work-dir

  spark:
    depends_on: 
      - spark-builder
    image: apache/spark-py
    volumes:
      - ./spark:/opt/spark/work-dir/spark-apps
      - ./data:/opt/spark/work-dir/data
    command: ["/opt/spark/bin/spark-submit", "--py-files", "/opt/spark/work-dir/spark-apps/src.zip,/opt/spark/work-dir/spark-apps/rethinkdb.zip", "/opt/spark/work-dir/spark-apps/main.py"]
    networks:
      - rethinkdb-net


  scraper:
    build: ./scraper
    env_file: 
      - ./scraper/.env
    depends_on:
      - kafka-broker
    networks:
      - kafka-net

  kafka-broker:
    image: apache/kafka:3.7.0
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - ./kafka/config:/mnt/shared/config
    environment:
      CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-broker:29093"
      KAFKA_LISTENERS: "PLAINTEXT_HOST://:9092,SSL://:9093,CONTROLLER://:29093,PLAINTEXT://:19092"
    networks:
      - kafka-net

  datasets-downloader:
    profiles:
      - datasets
    build: ./data
    volumes:
      - ./data:/data  # Mount host directory `./data` to container's `/data`
      - $HOME/.kaggle:/root/.kaggle:ro  # Mount Kaggle credentials as read-only

networks:
  kafka-net:
    driver: bridge
  rethinkdb-net:
    driver: bridge